Makefile
c68870ffc0409c29eece5ba036c6efd3c22cee41^...v1.0.1.patch
mercury.spec

Since we have discovered issues with 1.0.1.
Signed-off-by: Brian J. Murrell <brian.murrell@intel.com>

Roll back our 1.0.1 to c68870f

---

Makefile
debian/changelog
mercury.spec
rollback-version.patch

Because that's a lot closer to what we really are building.

CART-89: Roll back the version to 1.0.1

---

Jenkinsfile
Makefile
packaging/Makefile_packaging.mk

Add Ubuntu rolling version build.
Signed-off-by: John E Malmberg <john.e.malmberg@intel.com>

CORCI-668 build: Add Ubuntu build

---

Jenkinsfile
Makefile
debian/changelog
f0b9f992793be46f1c6ae47b30d1c3ccb525cfbf...616fee16a3c09eb93d804b627e64ea1c84c6b4d4.patch
mercury.spec
packaging/Makefile_packaging.mk

Update to 616fee

---

debian/changelog
mercury.spec

Fix mercury.spec to apply patch #3

---

616fee16a3c09eb93d804b627e64ea1c84c6b4d4...6a8b69349a530a708a4ae26937205922016eb3ed.patch
Makefile
debian/changelog
mercury.spec

Update to latest mercury commit 6a8b69

---

packaging/Dockerfile.mockbuild
packaging/Makefile_packaging.mk

Update to packaging

---

616fee16a3c09eb93d804b627e64ea1c84c6b4d4...7b529b63e4003fb15ebdbf2dfdf29ab2a3d3c132.patch
Makefile
debian/changelog
mercury.spec

Update to 7b529b

---

Makefile
debian/changelog
mercury.spec
mercury_combined_7b529b.patch
packaging/Makefile_packaging.mk

Manual sl patch on top of 7b529b to split ofi domain from ofi
interface in the mercury

CART-716 ofi: Manual sl patch on top of 7b529b.patch

---

c2c262813811c3ede28ee32fdebbffd417a7cb80..bb3fafb15ffab4c2b7a84d3262cc439435526ee8.patch
mercury.spec

Fix a bug in the name server patch

CART-89 build: update nameserver patch

---

mercury.spec
v2.0.0a1..299b06d47e6c1d59a45985dcbbebe3caca0189d0.patch

Update to 299b06d47e6c1d59a45985dcbbebe3caca0189d0 to pull in
rpc cancellation fixes

CART-89 merc: Update to 299b06d47e6c1d59a45985dcbbebe3caca0189d0

---

mercury.spec
v2.0.0a1..41caa143a07ed179a3149cac4af0dc7aa3f946fd.patch

CART-89 mercury: Update to 41caa1

---

mercury.spec
v2.0.0a1..4871023058887444d47ead4d089c99db979f3d93.patch

- Update mercury to 4871023058887444d47ead4d089c99db979f3d93 to pick
race condition fix in na_ofi.c

CART-89 update: Update to 4871023058887444d47ead4d089c99db979f3d93

---

mercury.spec

Signed-off-by: Brian J. Murrell <brian.murrell@intel.com>

Fix License and add %license

---

Jenkinsfile

Signed-off-by: Brian J. Murrell <brian.murrell@intel.com>

Set publish_branch

---

mercury.spec

Signed-off-by: Brian J. Murrell <brian.murrell@intel.com>

Bump Release: according to previous commit

---

Makefile
debian/changelog
mercury.spec
packaging/Makefile_packaging.mk

CART-89 mercury: Update to v2.0.0rc2

---

Makefile
debian/changelog
mercury.spec

CART-89 mercury: Update mercury to 2.0.0rc3

---

Makefile
debian/changelog
mercury.spec
packaging/Makefile_packaging.mk

CART-89 mercury: Update to mercury 2.0.0

---

packaging/Dockerfile.mockbuild
packaging/Makefile_distro_vars.mk
packaging/Makefile_packaging.mk
packaging/rpm_chrootbuild

Update packaging scripts to be able to use a local repository
for the distro provided repositories.
Signed-off-by: John E Malmberg <john.e.malmberg@intel.com>

DAOS-7813 Build: Update Packaging scripts

---

debian/changelog
mercury.spec

CART-89 mercury: Update to v2.0.1

---

packaging/Dockerfile.centos.7
packaging/Dockerfile.ubuntu.20.04
packaging/Makefile_distro_vars.mk
packaging/Makefile_packaging.mk
packaging/rpm_chrootbuild

Update packaging to add builds for CentOS 8.4 and Leap 15.3
Signed-off-by: John E Malmberg <john.e.malmberg@intel.com>

CORCI-1103 Build: Update packaging

---

debian/changelog
mercury.spec
packaging/Dockerfile.centos.7
packaging/Dockerfile.coverity
packaging/Dockerfile.mockbuild
packaging/Dockerfile.ubuntu.20.04
packaging/Dockerfile.ubuntu.rolling
packaging/Jenkinsfile
packaging/Makefile
packaging/Makefile_distro_vars.mk
packaging/Makefile_packaging.mk
packaging/README.md
packaging/debian_chrootbuild
packaging/install
packaging/rpm_chrootbuild

CART-89 mercury: Update mercury to v2.1.0rc2

---

daos_9173_workaround.patch
debian/changelog
mercury.spec

- Apply daos-9173 patch workaround to mercury
Signed-off-by: Alexander A Oganezov <alexander.a.oganezov@intel.com>

DAOS-9173 mercury: Apply patch

---

cpu_usage.patch
debian/changelog
mercury.spec

- Apply cpu utilization fix
Signed-off-by: Alexander A Oganezov <alexander.a.oganezov@intel.com>

CART-89 mercury: apply cpu utilization fix

---

.github/CODEOWNERS
Jenkinsfile
mercury.spec
packaging/Dockerfile.mockbuild
packaging/Makefile_distro_vars.mk
packaging/Makefile_packaging.mk

DAOS-9319 packaging: Fix ldconfig scriptlets
Some general clean up.

DAOS-9796: Build for el8 rather than centos8

---

debian/changelog
mercury.spec
na_ucx.patch

Signed-off-by: Joseph Moore <joseph.moore@intel.com>

DAOS-12032 mercury: Add reconnect to UCX.

---

debian/changelog
mercury.spec
packaging/Dockerfile.mockbuild
packaging/Dockerfile.ubuntu.20.04
packaging/Makefile_distro_vars.mk
packaging/Makefile_packaging.mk
packaging/debian_chrootbuild
packaging/rpm_chrootbuild

- Generate LEAP15.4 rpms
Signed-off-by: Alexander A Oganezov <alexander.a.oganezov@intel.com>

DAOS-12210 mercury: Update packages for LEAP15.4

---

Jenkinsfile
debian/changelog
debian/control
mercury.spec

add json-c dependency for hg_info JSON output support
drop support for CentOS7

DAOS-14565 mercury: update to 2.3.1

---

debian/changelog
hg_util_dlog_free.patch
mercury.spec
na_ofi_cxi_warning.patch
na_ucx_get_info.patch
packaging/Dockerfile.mockbuild
packaging/Makefile_packaging.mk
packaging/ccache-stats.patch
packaging/get_base_branch
packaging/rpm_chrootbuild

add patch to remove ofi cxi MR warnings

DAOS-15470 mercury: add patch to fix ucx hg_info

---

Jenkinsfile
LICENSE
Makefile

SRE-2515: New LICENSE file as expected by OpenSSF Scorecard

---

debian/changelog
debian/control
mercury.spec
packaging/get_base_branch

Update required libfabric version (>= 1.20)
PR-repos: libfabric@PR-77:lastBuild

DAOS-16752 mercury: update to mercury 2.4.0
